version: "3.7"
services:
    apfphelper:
        container_name: apfphelper
        restart: unless-stopped
        environment:
            - NODE_ENV=production
            - token=
            - guildId=
            - clientId=
            - mongoIp=
        image: p0rtl/apfphelper
